### ISSUE TITLE
Push to Openshift is broken again...

### ISSUE THREAD

**Issue by decause** [ryansb/ofCourse#32]
$ ofcourse openshift --app hfoss --user remy@magic.rit.edu
/home/decause/.virtualenvs/ofcourse/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/home/decause/.virtualenvs/ofcourse/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
Openshift password: 
Traceback (most recent call last):
  File "/home/decause/.virtualenvs/ofcourse/bin/ofcourse", line 10, in <module>
    sys.exit(cli())
  File "/home/decause/.virtualenvs/ofcourse/lib/python2.7/site-packages/click/core.py", line 610, in __call__
    return self.main(*args, **kwargs)
  File "/home/decause/.virtualenvs/ofcourse/lib/python2.7/site-packages/click/core.py", line 590, in main
    rv = self.invoke(ctx)
  File "/home/decause/.virtualenvs/ofcourse/lib/python2.7/site-packages/click/core.py", line 936, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/decause/.virtualenvs/ofcourse/lib/python2.7/site-packages/click/core.py", line 782, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/decause/.virtualenvs/ofcourse/lib/python2.7/site-packages/click/core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "/home/decause/.virtualenvs/ofcourse/lib/python2.7/site-packages/ofcourse/cli/__init__.py", line 115, in openshift
    token = generate_token(user, password)
  File "/home/decause/.virtualenvs/ofcourse/lib/python2.7/site-packages/ofcourse/cli/openshift_utils.py", line 147, in generate_token
    session.text))
Exception: Uhoh 401 response=HTTP Basic: Access denied.

**Comment by ryansb** [comment]
Uh, this is the openshift response for a wrong password.

**Comment by ryansb** [comment]
a.k.a. please try again with the right email/password combo for that openshift account.

**Comment by decause** [comment]
The password authentication itself is new behavior, as it was not required
for me to enter it, even a week ago. Yacht outage may be a contributing
factor...

**Comment by ryansb** [comment]
The yacht outage is not related, ofcourse doesn't depend on yacht things. 

The reason you haven't seen the password prompt for a while is because ofCourse uses your password to get a token which then lasts for (I think) 3 months. a.k.a. plenty of time for you to forget your password.

**Comment by ryansb** [comment]
@decause did you resolve this?

**Comment by ryansb** [comment]
Closing since original reporter hasn't responded for 2 weeks.
